version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  build:
    commands:
      - printenv > .env

artifacts:
  files:
    - '**/*'
  discard-paths: no
